### ISSUE TITLE
Error importing as ES Module with TypeScript

### ISSUE THREAD

**Issue by russellsteadman** [Vexcited/solid-hcaptcha#2]
Typescript raises an error because it is unable to find a corresponding type. It looks like the `package.json` is missing the `types` entry under `exports`. See the [TypeScript docs](https://www.typescriptlang.org/docs/handbook/esm-node.html#packagejson-exports-imports-and-self-referencing) for more context (scroll to the bottom).

**Comment by Vexcited** [comment]
Hi! Thanks you for the report, please try to upgrade to the [0.4.0](https://github.com/Vexcited/solid-hcaptcha/releases/tag/v0.4.0) and see if the issue is fixed.

**Comment by Vexcited** [comment]
Closing since stale, feel free to reopen if the issue persists.
